name: Auto approve
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.PAT }}
