name: auto-approve
on: 
  push:
  pull_request:
    branches:
      - 'update-release-metadata'

jobs:
  autoApprove:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      - name: Pull request number
        run: |
          echo "Pull Request Number - ${{ github.event.pull_request.number }}"

      - name: Approve pull Request
        if: ${{ github.event.pull_request.number }}
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}

