name: auto-approve
on:
  pull_request_target:
    branches:
      - dev # targets branch dev

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v3
