name: Build and test DEV

on:
  workflow_dispatch:
    inputs:
      ENV:
        description: environment to build and test
        default: dev
        required: false
      PIPELINE:
        description: pipeline to run
        default: build-execute
        required: false
  workflow_call:



jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      actions: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build-and-test-dev
        run: |
          echo 'This is where we build and test our container image.'
      - uses: ReeganExE/github-action-job-id@v1.0
      - run: |
          echo $GH_JOB_0_ID
      - name: Parse logs
        run: |
          STRING_PARSED_FROM_LOG=$(gh api -i '/repos/orphefs/gh-workflow-examples/actions/jobs/${{ steps.run_tests.outputs.* }}/logs' | grep "This is where")
          echo $STRING_PARSED_FROM_LOG
        env:
          GH_TOKEN: ${{ github.token }}
