name: Build and test DEV

on:
  workflow_dispatch:
    inputs:
      ENV:
        description: environment to build and test
        default: dev
        required: false
      PIPELINE:
        description: pipeline to run
        default: build-execute
        required: false
  push:
    branches:
      - feature-refactor
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: build-and-test
        run: |
          echo 'This is where the magic happens.'
