name: build-execute-after-update-release-metadata
on:
  push:
    branches:
      - dev
      - main

jobs:
  call-build-test-workflow-dev:
    if: |
      ${{ github.ref == 'refs/heads/dev' }} && 
      startsWith(github.event.head_commit.message, 'Merge pull request') == true &&
      contains(github.event.head_commit.message, 'update-release-metadata-') == true
    uses: ./.github/workflows/tekton-build-test-dev.yaml
  call-build-test-workflow-prod:
    if: |
      ${{ github.ref == 'refs/heads/main' }} && 
      startsWith(github.event.head_commit.message, 'Merge pull request') == true && 
      contains(github.event.head_commit.message, 'update-release-metadata-') == true
    uses: ./.github/workflows/tekton-build-test-prod.yaml
