name: Build and test DEV

on:
  workflow_dispatch:
    inputs:
      ENV:
        description: environment to build and test
        default: dev
        required: false
      PIPELINE:
        description: pipeline to run
        default: build-execute
        required: false
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      actions: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build-and-test-dev
        run: |
          echo 'This is where we build and test our container image.'
      - uses: ReeganExE/github-action-job-id@v1.0
      - run: |
          echo $GH_JOB_0_ID
          env | grep GH_JOB
          STRING_PARSED_FROM_LOG=$(gh api -i '/repos/orphefs/gh-workflow-examples/actions/jobs/$GH_JOB_0_ID/logs' | grep "This is where")
          echo $STRING_PARSED_FROM_LOG
          
