name: Build and test DEV

on:
  workflow_dispatch:
    inputs:
      ENV:
        description: environment to build and test
        default: dev
        required: false
      PIPELINE:
        description: pipeline to run
        default: build-execute
        required: false
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build-and-test-dev
        run: |
          echo 'This is where we build and test our container image.'
      - name: Get Current Job Log URL
        uses: Tiryoh/gha-jobid-action@v0
        id: jobs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: build-and-test-dev
          per_page: 30
      - name: Output Current Job Log URL
        run: echo ${{ steps.jobs.outputs.html_url }}
