name: update-release-metadata
on:
  push:
    branches:
      - dev
      - main

jobs:
  run_if:
    if: startsWith(github.event.head_commit.message, "Merge pull request") != true && contains(github.event.head_commit.message, 'update-release-metadata-') != true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: update-release-metadata
        run: |
          echo "$(git rev-parse HEAD)" >> RELEASE

      - name: Create pull request
        id: create-pr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: update release metadata
          title: Update release metadata
          body: Update release metadata to reflect release changes
          branch: update-release-metadata
          labels: automerge
          branch-suffix: short-commit-hash
          base: ${{ github.ref_name }}

      - name: Approve pull request
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.PAT }}
          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}

      - name: Merge pull request
        run: |
          gh pr merge $pullRequestNumber --merge
        env:
          GH_TOKEN: ${{ secrets.PAT }}
          sha: ${{ steps.get-commits.outputs.latest_commit_sha }}
          labels: automerge
          token: ${{ secrets.PAT }}
          pullRequestNumber: ${{ steps.create-pr.outputs.pull-request-number }}
